### ISSUE TITLE
NIM Series 01 - Auto Login was Never work.

### ISSUE THREAD

**Issue by Ricotan-Linus** [Yanorei32/nnn-improved#3]
SSIA. 多分ログイン方法変更の影響.

**Comment by yanorei32** [comment]
It's works in my environments.

## Env A
|-|-|
|:--|:--|
|Tampermonkey|v4.10.6105|
|Firefox Browser NIGHTLY|76.0a1 (2020-04-01) (64-bit)|
|Windows Server 2019 Datacenter|1809 17763.1098|

## Env B
|-|-|
|:--|:--|
|Tampermonkey|v4.10.6105|
|Firefox Browser NIGHTLY|76.0a1 (2020-03-28) (64-bit)|
|Windows 10 Home|1909 18363.752|

## Env C
|-|-|
|:--|:--|
|Tampermonkey|v4.10.6105|
|Firefox Browser NIGHTLY|76.0a1 (2020-04-02) (64-bit)|
|Windows 10 Pro|1909 18363.752|

Please tell me your environment.

and "was Never work"? Is it working now?

**Comment by yanorei32** [comment]
I tested chromium environment and it works.

## Env D
|-|-|
|:--|:--|
|Tampermonkey|v4.10.6111|
|Microsoft Edge|80.0.361.109 (Offcial build) (64-bit)|
|Windows Server 2019 Datacenter|1809 17763.1098|

**Comment by yanorei32** [comment]
I tested edge environment and it works.

## Env E
|-|-|
|:--|:--|
|Tampermonkey|v4.9.5942|
|Microsoft Edge, Microsoft EdgeHTML|44.18362.449.0, 18.18363|
|Windows 10 Home|1909 18363.752|

**Comment by Ricotan-Linus** [comment]
取り下げ。原因不明だが再インストールし動作確認。Windows Server 2019 Datacenter。TampermonkeyのVer確認していない。Firefox Nightlyも同様。
